sonar.projectKey=hansss22_modul3-103022330167
sonar.organization=hansss22


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=modul3_103022330167
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8